# Generated by Django 4.0.4 on 2022-05-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef_Service',
            fields=[
                ('Matricule', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Date_recrutement', models.DateField()),
                ('salaire', models.FloatField(default=8000)),
                ('email', models.CharField(max_length=40)),
                ('mdp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('Matricule', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('Date_recrutement', models.DateTimeField(auto_now_add=True)),
                ('salaire', models.FloatField(default=2500)),
                ('email', models.CharField(max_length=40)),
                ('mdp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id_Equipe', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Equipe', models.CharField(max_length=80)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('chef_Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouchTask.chef_service')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('NomProjet', models.CharField(max_length=80)),
                ('Description', models.CharField(max_length=30000)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('Dead_Line', models.DateField()),
                ('Equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouchTask.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_tache', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_tache', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=30000)),
                ('date_lancement', models.DateTimeField(auto_now_add=True)),
                ('Etat', models.CharField(choices=[('fin', 'FIN'), ('en cours', 'EN COURS')], default='En attente', max_length=20)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouchTask.employe')),
                ('Projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouchTask.projet')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='Equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TouchTask.equipe'),
        ),
    ]
